pipeline {
    agent any

	// Подключаем созданные секреты к переменным окружения
    environment {
        DB_USER = credentials('DB_USER_SECRET')
        DB_PASS = credentials('DB_PASS_SECRET')
        DB_NAME = credentials('DB_NAME_SECRET')
    }

    stages {
        stage('Checkout') {
            steps {
                // Шаг 1: Получаем актуальный код из GitHub
                checkout scm
            }
        }

		stage('Security Check (Quality Gate)') {
            steps {
                echo 'Auditing only project requirements...'
                // Устанавливаем pip-audit и Флаг --no-deps поможет не зарываться в системные библиотеки
				sh "pip install pip-audit --break-system-packages && pip-audit --local -r dv_project_4/CryptoDash_CI/requirements.txt || echo 'Сетевая ошибка аудита, но идем дальше'"
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Crypto Dash Image...'
                // Шаг 3: Сборка образа.
                sh 'docker build -t crypto-dash:latest dv_project_4/CryptoDash_CI/'
            }
        }

        stage('Test Run') {
            steps {
                echo 'Testing: checking if container starts...'
                // Шаг 4: Проверяем, что контейнер запускается
                sh 'docker run --rm crypto-dash:latest python --version'
            }
        }

		stage('Deploy Infrastructure') {
            steps {
                echo 'Starting Fresh Database and App...'
                sh """
                # 1. Останавливаем всё старое
                docker stop crypto-db crypto-app || true
                docker rm crypto-db crypto-app || true
                
                # 2. Запускаем НОВУЮ чистую базу данных
                docker run -d --name crypto-db \
                  -e POSTGRES_USER=${DB_USER} \
                  -e POSTGRES_PASSWORD=${DB_PASS} \
                  -e POSTGRES_DB=${DB_NAME} \
                  -p 5433:5432 postgres:15-alpine
                
                # Даем базе 10 секунд, чтобы проснуться
                sleep 10
				"""
			}
		}

		stage('ETL: Load Data') {
            steps {
                echo 'Installing dependencies and running ETL...'
                sh """
                # Устанавливаем библиотеку для работы с БД (используем binary версию, она проще ставится)
                pip install --break-system-packages psycopg2-binary pandas
                
                # Запускаем сам скрипт загрузки
                python3 dv_project_4/CryptoDash_CI/data_loader.py
                """
            }
        }

		stage('ETL: Load Data') {
            steps {
                echo 'Loading data into the NEW database...'
                // 3. Запускаем Дашборд, подключая его к этой новой базе
                sh """
                docker run -d --name crypto-app -p 8501:8501 --link crypto-db:db_server \
                  -e DB_HOST=db_server \
                  -e DB_NAME=${DB_NAME} \
                  -e DB_USER=${DB_USER} \
                  -e DB_PASSWORD=${DB_PASS} \
                  crypto-dash:latest
                """
            }
        }
    }
}
