pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Шаг 1: Получаем актуальный код из GitHub
                checkout scm
            }
        }

        stage('Security Check (Quality Gate)') {
            steps {
                echo 'Checking for vulnerable dependencies...'
                // Шаг 2: Установка pip-audit и проверка безопасности библиотек
                // Мы специально добавим старую библиотеку, чтобы этот шаг "заругался"
                sh 'pip install pip-audit --break-system-packages && pip-audit --local -r dv_project_4/CryptoDash_CI/requirements.txt'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Crypto Dash Image...'
                // Шаг 3: Сборка образа. Указываем путь к папке с Dockerfile
                sh 'docker build -t crypto-dash:latest ./CryptoDash_CI/dockerfile'
            }
        }

        stage('Test Run') {
            steps {
                echo 'Testing: checking if container starts...'
                // Шаг 4: Проверяем, что контейнер запускается
                sh 'docker run --rm crypto-dash:latest python --version'
            }
        }
    }
}

