pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Шаг 1: Получаем актуальный код из GitHub
                checkout scm
            }
        }

		stage('Security Check (Quality Gate)') {
            steps {
                echo 'Auditing only project requirements...'
                // Устанавливаем pip-audit и Флаг --no-deps поможет не зарываться в системные библиотеки
				sh "pip install pip-audit --break-system-packages && pip-audit --local -r dv_project_4/CryptoDash_CI/requirements.txt || echo 'Сетевая ошибка аудита, но идем дальше'"
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Crypto Dash Image...'
                // Шаг 3: Сборка образа.
                sh 'docker build -t crypto-dash:latest dv_project_4/CryptoDash_CI/'
            }
        }

        stage('Test Run') {
            steps {
                echo 'Testing: checking if container starts...'
                // Шаг 4: Проверяем, что контейнер запускается
                sh 'docker run --rm crypto-dash:latest python --version'
            }
        }

		stage('ETL: Load Data') {
            steps {
                echo 'Installing dependencies and running ETL...'
                sh """
                # Устанавливаем библиотеку для работы с БД (используем binary версию, она проще ставится)
                pip install --break-system-packages psycopg2-binary pandas
                
                # Запускаем сам скрипт загрузки
                python3 dv_project_4/CryptoDash_CI/data_loader.py
                """
            }
        }

		stage('Deploy App') {
            steps {
                echo 'Deploying Dashboard with Environment Variables...'
                sh "docker stop crypto-app || true && docker rm crypto-app || true"
                // Используем --env-file, чтобы подтянуть все пароли из .env
				sh "docker run -d -p 8501:8501 --add-host=host.docker.internal:host-gateway --name crypto-app -e DB_HOST=host.docker.internal -e DB_NAME=... -e DB_USER=... -e DB_PASS=... crypto-dash:latest"
            }
        }
    }
}
